### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by androidacy-user** [Librefox/librefox-website#3] opened 2019-01-09 15:52 UTC
Here we can decide what the logo should look like.
I'm thinking a material dark version of the Firefox icon(fox) with a broken chain dangling from it(Libre) 

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intika** [comment] 2019-01-09 15:54
it's a duplicate of https://github.com/intika/Librefox/issues/20

**Closed as completed by intika** 2019-01-09 15:54 UTC
